### ISSUE TITLE
Add description, heroku URL and topic tags

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/532_Dashboard_Project_Group_14#36]
Hey! Just a reminder to fill out your about section with a description, the heroku app URL and some topic tags describing your app. I will use these to create a gallery of the dashboards. [See my repo for an example](https://github.com/UBC-MDS/dashr-heroku-deployment-demo)

![image](https://user-images.githubusercontent.com/4560057/107132012-6db3a080-6890-11eb-9daa-cbf7343ff6f9.png)

**Comment by ChuckHo777** [comment]
Thanks for the reminder. It is now added.

**Comment by joelostblom** [comment]
Great!
